import { Injectable, BadRequestException } from '@nestjs/common';
import { MatchScoreService } from './services/match-score.service';
import { BudgetMatcherService } from './services/budget-matcher.service';
import {
  MatchWeights,
  UniversityProgramRecord,
  UniversityMatchResult,
} from './types/matcher.types';
import { UniversityMatchSearchDto, UpdateWeightsDto } from './dto/university-match.dto';

@Injectable()
export class UniversityMatcherService {
  private weights: MatchWeights = {
    course: 30,
    country: 20,
    studyLevel: 15,
    budget: 15,
    english: 10,
    intake: 5,
    eligibility: 5,
  };

  // Comprehensive verified benchmark demo dataset (Flagged isDemoData: true)
  private programsDatabase: UniversityProgramRecord[] = [
    // UK
    {
      id: 'prog-uk-1',
      universityId: 'uni-birmingham',
      universityName: 'University of Birmingham',
      universitySlug: 'university-of-birmingham',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
      country: 'United Kingdom',
      city: 'Birmingham',
      destinationCode: 'UK',
      courseName: 'MSc Advanced Computer Science',
      courseCategory: 'Computer Science & IT',
      studyLevel: "Master's",
      duration: '1 Year Full-Time',
      tuitionFeeLocal: '£27,500 / year',
      tuitionInrLakhs: { min: 28, max: 32 },
      currency: 'GBP',
      intakes: ['September 2026', 'January 2027'],
      eligibility: 'Bachelor degree in CS / IT with minimum 60% aggregate. IELTS 6.5 minimum (no band < 6.0).',
      applicationDeadline: '30 June 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 62,
        ptePreferred: 68,
        toeflMin: 88,
        toeflPreferred: 95,
        duolingoMin: 120,
        duolingoPreferred: 130,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Aegis Global Excellence Scholarship worth £3,000 – £5,000 tuition reduction.',
      ranking: 84,
      featured: true,
      status: 'ACTIVE',
      description: 'A prestigious Russell Group institution offering cutting-edge computing laboratories, AI industry placements, and strong global employer connections in the UK tech hub.',
      website: 'https://www.birmingham.ac.uk',
      isDemoData: true,
    },
    {
      id: 'prog-uk-2',
      universityId: 'uni-oxford',
      universityName: 'University of Oxford',
      universitySlug: 'university-of-oxford',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=800&auto=format&fit=crop',
      country: 'United Kingdom',
      city: 'Oxford',
      destinationCode: 'UK',
      courseName: 'MSc Computer Science',
      courseCategory: 'Computer Science & IT',
      studyLevel: "Master's",
      duration: '1 Year Full-Time',
      tuitionFeeLocal: '£36,500 / year',
      tuitionInrLakhs: { min: 38, max: 45 },
      currency: 'GBP',
      intakes: ['October 2026'],
      eligibility: 'First class undergraduate degree in mathematics, computer science or engineering. IELTS 7.5 minimum.',
      applicationDeadline: '20 January 2026',
      englishReq: {
        ieltsMin: 7.5,
        ieltsPreferred: 8.0,
        pteMin: 76,
        ptePreferred: 82,
        toeflMin: 110,
        toeflPreferred: 115,
        duolingoMin: 140,
        duolingoPreferred: 150,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Clarendon Fund and Oxford Graduate Scholarships for high academic merit.',
      ranking: 1,
      featured: true,
      status: 'ACTIVE',
      description: 'World-renowned collegiate research university offering peerless academic rigor, historic libraries, and premier academic mentorship.',
      website: 'https://www.ox.ac.uk',
      isDemoData: true,
    },
    {
      id: 'prog-uk-3',
      universityId: 'uni-leeds',
      universityName: 'University of Leeds',
      universitySlug: 'university-of-leeds',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
      country: 'United Kingdom',
      city: 'Leeds',
      destinationCode: 'UK',
      courseName: 'MSc International Business & Finance',
      courseCategory: 'Business Administration',
      studyLevel: "Master's",
      duration: '1 Year Full-Time',
      tuitionFeeLocal: '£26,000 / year',
      tuitionInrLakhs: { min: 26, max: 30 },
      currency: 'GBP',
      intakes: ['September 2026'],
      eligibility: 'Bachelor degree in any discipline with 60%+. IELTS 6.5 with 6.0 in all bands.',
      applicationDeadline: '30 June 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 64,
        ptePreferred: 70,
        toeflMin: 92,
        toeflPreferred: 100,
        duolingoMin: 120,
        duolingoPreferred: 130,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Dean’s International Excellence Award £4,000.',
      ranking: 75,
      featured: false,
      status: 'ACTIVE',
      description: 'Triple-accredited Leeds University Business School recognized for international commerce and corporate financial strategy.',
      website: 'https://www.leeds.ac.uk',
      isDemoData: true,
    },

    // USA
    {
      id: 'prog-usa-1',
      universityId: 'uni-asu',
      universityName: 'Arizona State University',
      universitySlug: 'arizona-state-university',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800&auto=format&fit=crop',
      country: 'United States',
      city: 'Tempe, Arizona',
      destinationCode: 'USA',
      courseName: 'MS in Data Science & Artificial Intelligence',
      courseCategory: 'Data Science',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '$34,000 / year',
      tuitionInrLakhs: { min: 28, max: 34 },
      currency: 'USD',
      intakes: ['August 2026 (Fall)', 'January 2027 (Spring)'],
      eligibility: 'Bachelor in STEM discipline with minimum 3.0/4.0 GPA. IELTS 6.5 or Duolingo 115.',
      applicationDeadline: '15 March 2026 (Fall)',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 60,
        ptePreferred: 65,
        toeflMin: 85,
        toeflPreferred: 92,
        duolingoMin: 115,
        duolingoPreferred: 125,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'New American University Scholar Award up to $10,000 annually.',
      ranking: 121,
      featured: true,
      status: 'ACTIVE',
      description: 'Ranked #1 in innovation in the US, ASU provides STEM-designated degree programs with 3-year OPT work eligibility and strong Silicon Valley and Phoenix tech recruitment.',
      website: 'https://www.asu.edu',
      isDemoData: true,
    },
    {
      id: 'prog-usa-2',
      universityId: 'uni-northeastern',
      universityName: 'Northeastern University',
      universitySlug: 'northeastern-university',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800&auto=format&fit=crop',
      country: 'United States',
      city: 'Boston, Massachusetts',
      destinationCode: 'USA',
      courseName: 'Master of Science in Information Systems',
      courseCategory: 'Information Technology',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '$38,500 / year',
      tuitionInrLakhs: { min: 32, max: 38 },
      currency: 'USD',
      intakes: ['September 2026', 'January 2027'],
      eligibility: 'Undergraduate STEM degree with 3.2+ GPA. IELTS 7.0 minimum or TOEFL 95.',
      applicationDeadline: '15 April 2026',
      englishReq: {
        ieltsMin: 7.0,
        ieltsPreferred: 7.5,
        pteMin: 68,
        ptePreferred: 74,
        toeflMin: 95,
        toeflPreferred: 102,
        duolingoMin: 125,
        duolingoPreferred: 135,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Khoury Graduate Merit Fellowship ($5,000 – $15,000).',
      ranking: 53,
      featured: true,
      status: 'ACTIVE',
      description: 'World-famous Co-op program integrating paid 6-month corporate placements with leading US tech giants, finance institutions, and healthcare providers.',
      website: 'https://www.northeastern.edu',
      isDemoData: true,
    },
    {
      id: 'prog-usa-3',
      universityId: 'uni-uta',
      universityName: 'University of Texas at Arlington',
      universitySlug: 'university-of-texas-arlington',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
      country: 'United States',
      city: 'Arlington, Texas',
      destinationCode: 'USA',
      courseName: 'MS in Mechanical Engineering',
      courseCategory: 'Mechanical Engineering',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '$21,500 / year',
      tuitionInrLakhs: { min: 18, max: 22 },
      currency: 'USD',
      intakes: ['Fall (August) 2026', 'Spring (January) 2027'],
      eligibility: 'B.Tech Mechanical / Automobile 65%+ marks. IELTS 6.5 or Duolingo 110.',
      applicationDeadline: '01 June 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 58,
        ptePreferred: 64,
        toeflMin: 80,
        toeflPreferred: 90,
        duolingoMin: 110,
        duolingoPreferred: 120,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Competitive In-State Tuition Waiver scholarship worth $14,000/year.',
      ranking: 240,
      featured: false,
      status: 'ACTIVE',
      description: 'High-value Carnegie R1 research university in the Dallas-Fort Worth metropolitan area with massive aerospace and industrial manufacturing presence.',
      website: 'https://www.uta.edu',
      isDemoData: true,
    },

    // Canada
    {
      id: 'prog-ca-1',
      universityId: 'uni-toronto',
      universityName: 'University of Toronto',
      universitySlug: 'university-of-toronto',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1568792923760-d70635a89fa8?q=80&w=800&auto=format&fit=crop',
      country: 'Canada',
      city: 'Toronto, Ontario',
      destinationCode: 'CANADA',
      courseName: 'Master of Science in Applied Computing (MScAC)',
      courseCategory: 'Computer Science & IT',
      studyLevel: "Master's",
      duration: '16 Months (incl. 8-month paid internship)',
      tuitionFeeLocal: 'CAD $48,000 / total',
      tuitionInrLakhs: { min: 28, max: 35 },
      currency: 'CAD',
      intakes: ['September 2026'],
      eligibility: 'B.Sc / B.Tech in CS or Software Eng with B+ (77%+) average. IELTS 7.0 minimum with no band below 6.5.',
      applicationDeadline: '01 December 2025',
      englishReq: {
        ieltsMin: 7.0,
        ieltsPreferred: 7.5,
        pteMin: 68,
        ptePreferred: 74,
        toeflMin: 93,
        toeflPreferred: 100,
        duolingoMin: 125,
        duolingoPreferred: 135,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Paid industrial R&D internship averaging CAD $55,000 stipends.',
      ranking: 21,
      featured: true,
      status: 'ACTIVE',
      description: 'Canada’s flagship academic institution, globally top-ranked for AI, machine learning and software engineering with direct Toronto tech corridor pathways.',
      website: 'https://www.utoronto.ca',
      isDemoData: true,
    },
    {
      id: 'prog-ca-2',
      universityId: 'uni-waterloo',
      universityName: 'University of Waterloo',
      universitySlug: 'university-of-waterloo',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1568792923760-d70635a89fa8?q=80&w=800&auto=format&fit=crop',
      country: 'Canada',
      city: 'Waterloo, Ontario',
      destinationCode: 'CANADA',
      courseName: 'Master of Management Sciences (MMSc)',
      courseCategory: 'Business Administration',
      studyLevel: "Master's",
      duration: '1–2 Years',
      tuitionFeeLocal: 'CAD $34,000 / year',
      tuitionInrLakhs: { min: 20, max: 25 },
      currency: 'CAD',
      intakes: ['September 2026', 'January 2027'],
      eligibility: 'Undergraduate degree with 75%+ average in engineering, science or commerce. IELTS 6.5 (6.0 writing).',
      applicationDeadline: '01 February 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 63,
        ptePreferred: 68,
        toeflMin: 90,
        toeflPreferred: 98,
        duolingoMin: 120,
        duolingoPreferred: 130,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'International Master’s Award of Excellence ($2,500/term).',
      ranking: 112,
      featured: true,
      status: 'ACTIVE',
      description: 'Renowned as Canada’s innovation university, blending data analytics, operations research, and tech startup entrepreneurship.',
      website: 'https://uwaterloo.ca',
      isDemoData: true,
    },

    // Australia
    {
      id: 'prog-au-1',
      universityId: 'uni-uow',
      universityName: 'University of Wollongong',
      universitySlug: 'university-of-wollongong',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=800&auto=format&fit=crop',
      country: 'Australia',
      city: 'Wollongong / Sydney, NSW',
      destinationCode: 'AUSTRALIA',
      courseName: 'Master of Computer Science (Intelligent Systems)',
      courseCategory: 'Computer Science & IT',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: 'AUD $38,500 / year',
      tuitionInrLakhs: { min: 20, max: 24 },
      currency: 'AUD',
      intakes: ['February 2026', 'July 2026'],
      eligibility: 'Bachelor degree in computing, engineering or mathematics. IELTS 6.5 (no band < 6.0) or PTE 60.',
      applicationDeadline: '30 November 2025 (Feb) / 31 May 2026 (July)',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 60,
        ptePreferred: 66,
        toeflMin: 86,
        toeflPreferred: 94,
        duolingoMin: 115,
        duolingoPreferred: 125,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'University of Wollongong 20%–30% International Tuition Fee Waiver.',
      ranking: 162,
      featured: true,
      status: 'ACTIVE',
      description: 'Top-tier Australian research university located 1 hour from Sydney, offering post-study work visa extensions (up to 4–5 years in regional category).',
      website: 'https://www.uow.edu.au',
      isDemoData: true,
    },
    {
      id: 'prog-au-2',
      universityId: 'uni-melbourne',
      universityName: 'University of Melbourne',
      universitySlug: 'university-of-melbourne',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=800&auto=format&fit=crop',
      country: 'Australia',
      city: 'Melbourne, Victoria',
      destinationCode: 'AUSTRALIA',
      courseName: 'Master of Engineering (Civil & Structural)',
      courseCategory: 'Civil Engineering',
      studyLevel: "Master's",
      duration: '2–3 Years',
      tuitionFeeLocal: 'AUD $49,000 / year',
      tuitionInrLakhs: { min: 26, max: 32 },
      currency: 'AUD',
      intakes: ['February 2026', 'July 2026'],
      eligibility: 'Four-year Bachelor of Engineering with 65%+ equivalent. IELTS 6.5 (6.0 in all bands).',
      applicationDeadline: '31 October 2025 / 30 April 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 62,
        ptePreferred: 68,
        toeflMin: 88,
        toeflPreferred: 96,
        duolingoMin: 120,
        duolingoPreferred: 130,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Melbourne Graduate Merit Scholarship (AUD $10,000).',
      ranking: 13,
      featured: true,
      status: 'ACTIVE',
      description: 'Australia’s #1 ranked university, member of the Group of Eight (Go8) with world-class engineering research facilities and Engineers Australia accreditation.',
      website: 'https://www.unimelb.edu.au',
      isDemoData: true,
    },

    // Germany
    {
      id: 'prog-de-1',
      universityId: 'uni-tum',
      universityName: 'Technical University of Munich (TUM)',
      universitySlug: 'technical-university-of-munich',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop',
      country: 'Germany',
      city: 'Munich, Bavaria',
      destinationCode: 'GERMANY',
      courseName: 'MSc Mechanical & Automotive Engineering',
      courseCategory: 'Mechanical Engineering',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '€0 (Tuition-Free, €150/sem fee)',
      tuitionInrLakhs: { min: 0, max: 4 },
      currency: 'EUR',
      intakes: ['Winter (October) 2026'],
      eligibility: 'B.Tech in Mechanical Engineering with high academic scores. GRE recommended. IELTS 6.5 / TOEFL 88.',
      applicationDeadline: '31 May 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 60,
        ptePreferred: 65,
        toeflMin: 88,
        toeflPreferred: 95,
        duolingoMin: 115,
        duolingoPreferred: 125,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'DAAD and Deutschlandstipendium living allowance support.',
      ranking: 37,
      featured: true,
      status: 'ACTIVE',
      description: 'Germany’s premier University of Excellence with close industrial partnerships including BMW, Siemens, and Audi. Tuition-free world-class education.',
      website: 'https://www.tum.de',
      isDemoData: true,
    },
    {
      id: 'prog-de-2',
      universityId: 'uni-rwth',
      universityName: 'RWTH Aachen University',
      universitySlug: 'rwth-aachen-university',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop',
      country: 'Germany',
      city: 'Aachen, North Rhine-Westphalia',
      destinationCode: 'GERMANY',
      courseName: 'MSc Computer Engineering & Information Technology',
      courseCategory: 'Computer Science & IT',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '€0 (Tuition-Free, €300 semester fee incl. transit)',
      tuitionInrLakhs: { min: 0, max: 4 },
      currency: 'EUR',
      intakes: ['Winter (October) 2026', 'Summer (April) 2027'],
      eligibility: 'Strong mathematical and computer science degree credits. IELTS 6.5 or TOEFL 90.',
      applicationDeadline: '01 March 2026 (Winter)',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 60,
        ptePreferred: 66,
        toeflMin: 90,
        toeflPreferred: 98,
        duolingoMin: 115,
        duolingoPreferred: 125,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Germany Deutschlandstipendium merit grants.',
      ranking: 106,
      featured: true,
      status: 'ACTIVE',
      description: 'Leading European technical university famous for cutting-edge robotics, high-performance computing, and automotive research.',
      website: 'https://www.rwth-aachen.de',
      isDemoData: true,
    },

    // Ireland
    {
      id: 'prog-ie-1',
      universityId: 'uni-tcd',
      universityName: 'Trinity College Dublin',
      universitySlug: 'trinity-college-dublin',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
      country: 'Ireland',
      city: 'Dublin',
      destinationCode: 'IRELAND',
      courseName: 'MSc Data Science & Intelligent Systems',
      courseCategory: 'Data Science',
      studyLevel: "Master's",
      duration: '1 Year Full-Time',
      tuitionFeeLocal: '€25,500 / year',
      tuitionInrLakhs: { min: 22, max: 26 },
      currency: 'EUR',
      intakes: ['September 2026'],
      eligibility: 'First-class honours degree in Computing, Maths or Statistics. IELTS 6.5 (no band below 6.0).',
      applicationDeadline: '30 June 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 63,
        ptePreferred: 68,
        toeflMin: 90,
        toeflPreferred: 98,
        duolingoMin: 120,
        duolingoPreferred: 130,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Global Excellence Postgraduate Scholarship €3,000 – €5,000.',
      ranking: 81,
      featured: true,
      status: 'ACTIVE',
      description: 'Ireland’s historic premier university located in Dublin’s Silicon Docks, home to European headquarters of Google, Meta, Apple, and Microsoft.',
      website: 'https://www.tcd.ie',
      isDemoData: true,
    },

    // New Zealand
    {
      id: 'prog-nz-1',
      universityId: 'uni-auckland',
      universityName: 'University of Auckland',
      universitySlug: 'university-of-auckland',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
      country: 'New Zealand',
      city: 'Auckland',
      destinationCode: 'NEW_ZEALAND',
      courseName: 'Master of Information Technology',
      courseCategory: 'Information Technology',
      studyLevel: "Master's",
      duration: '1.5–2 Years',
      tuitionFeeLocal: 'NZD $46,000 / year',
      tuitionInrLakhs: { min: 22, max: 26 },
      currency: 'NZD',
      intakes: ['February 2026', 'July 2026'],
      eligibility: 'Bachelor degree in IT or non-IT with B grade average. IELTS 6.5 (no band below 6.0).',
      applicationDeadline: '01 December 2025 / 01 May 2026',
      englishReq: {
        ieltsMin: 6.5,
        ieltsPreferred: 7.0,
        pteMin: 60,
        ptePreferred: 65,
        toeflMin: 90,
        toeflPreferred: 95,
        duolingoMin: 115,
        duolingoPreferred: 125,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'University of Auckland International Student Excellence Scholarship (NZD $10,000).',
      ranking: 68,
      featured: true,
      status: 'ACTIVE',
      description: 'Top-ranked university in New Zealand, providing a generous 3-year post-study work visa and excellent quality of life in Auckland.',
      website: 'https://www.auckland.ac.nz',
      isDemoData: true,
    },

    // Europe (Schengen)
    {
      id: 'prog-eu-1',
      universityId: 'uni-polimi',
      universityName: 'Politecnico di Milano',
      universitySlug: 'politecnico-di-milano',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop',
      country: 'Europe (Schengen)',
      city: 'Milan, Italy',
      destinationCode: 'EUROPE',
      courseName: 'MSc in Architectural Design & Technology',
      courseCategory: 'Architecture',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '€3,900 / year',
      tuitionInrLakhs: { min: 4, max: 7 },
      currency: 'EUR',
      intakes: ['September 2026', 'February 2027'],
      eligibility: 'Undergraduate Architecture degree with design portfolio. IELTS 6.0 or TOEFL 78.',
      applicationDeadline: '01 March 2026',
      englishReq: {
        ieltsMin: 6.0,
        ieltsPreferred: 6.5,
        pteMin: 55,
        ptePreferred: 62,
        toeflMin: 78,
        toeflPreferred: 88,
        duolingoMin: 105,
        duolingoPreferred: 115,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Platinum & Gold Merit scholarships covering full tuition and €10,000 living stipend.',
      ranking: 111,
      featured: true,
      status: 'ACTIVE',
      description: 'Europe’s top-tier technical university for architecture, industrial engineering, and design, situated in Italy’s financial and creative capital.',
      website: 'https://www.polimi.it',
      isDemoData: true,
    },
    {
      id: 'prog-eu-2',
      universityId: 'uni-delft',
      universityName: 'Delft University of Technology (TU Delft)',
      universitySlug: 'tu-delft',
      logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=200&auto=format&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop',
      country: 'Europe (Schengen)',
      city: 'Delft, Netherlands',
      destinationCode: 'EUROPE',
      courseName: 'MSc Electrical Engineering & Telecommunications',
      courseCategory: 'Electrical Engineering',
      studyLevel: "Master's",
      duration: '2 Years',
      tuitionFeeLocal: '€21,500 / year',
      tuitionInrLakhs: { min: 19, max: 23 },
      currency: 'EUR',
      intakes: ['September 2026'],
      eligibility: 'B.Tech in Electrical / Electronics Engineering with 75%+ GPA. IELTS 7.0 (no band below 6.5).',
      applicationDeadline: '15 January 2026',
      englishReq: {
        ieltsMin: 7.0,
        ieltsPreferred: 7.5,
        pteMin: 68,
        ptePreferred: 74,
        toeflMin: 100,
        toeflPreferred: 105,
        duolingoMin: 125,
        duolingoPreferred: 135,
      },
      scholarshipAvailable: true,
      scholarshipDetails: 'Justus & Louise van Effen Excellence Scholarships.',
      ranking: 47,
      featured: true,
      status: 'ACTIVE',
      description: 'Globally celebrated for engineering, quantum technology and semiconductor systems in the Dutch innovation hub.',
      website: 'https://www.tudelft.nl',
      isDemoData: true,
    },
  ];

  constructor(
    private readonly matchScoreService: MatchScoreService,
    private readonly budgetMatcherService: BudgetMatcherService
  ) {}

  getWeights(): MatchWeights {
    return { ...this.weights };
  }

  updateWeights(newWeights: UpdateWeightsDto): { success: boolean; weights: MatchWeights } {
    const sum =
      Number(newWeights.course) +
      Number(newWeights.country) +
      Number(newWeights.studyLevel) +
      Number(newWeights.budget) +
      Number(newWeights.english) +
      Number(newWeights.intake) +
      Number(newWeights.eligibility);

    if (Math.abs(sum - 100) > 0.01) {
      throw new BadRequestException(
        `Total weights must equal 100%. Current sum is ${sum}%.`
      );
    }

    this.weights = {
      course: Number(newWeights.course),
      country: Number(newWeights.country),
      studyLevel: Number(newWeights.studyLevel),
      budget: Number(newWeights.budget),
      english: Number(newWeights.english),
      intake: Number(newWeights.intake),
      eligibility: Number(newWeights.eligibility),
    };

    return { success: true, weights: this.weights };
  }

  getConfigOptions() {
    return {
      studyLevels: [
        'Undergraduate',
        'Postgraduate',
        "Master's",
        'MBA',
        'PhD',
        'Diploma',
        'Certificate',
      ],
      courses: [
        'Computer Science',
        'Information Technology',
        'Data Science',
        'Business Administration',
        'Finance',
        'Engineering',
        'Mechanical Engineering',
        'Civil Engineering',
        'Electrical Engineering',
        'Healthcare',
        'Nursing',
        'Pharmacy',
        'Architecture',
        'Hospitality',
      ],
      countries: [
        'United Kingdom (UK)',
        'United States (USA)',
        'Canada',
        'Australia',
        'Germany',
        'Ireland',
        'New Zealand',
        'Europe (Schengen)',
      ],
      englishTests: [
        { id: 'IELTS', label: 'IELTS', minScore: 0, maxScore: 9, step: 0.5, defaultScore: 6.5 },
        { id: 'PTE', label: 'PTE Academic', minScore: 10, maxScore: 90, step: 1, defaultScore: 65 },
        { id: 'TOEFL', label: 'TOEFL iBT', minScore: 0, maxScore: 120, step: 1, defaultScore: 90 },
        { id: 'Duolingo', label: 'Duolingo English Test', minScore: 10, maxScore: 160, step: 5, defaultScore: 120 },
        { id: 'OET', label: 'OET (Occupational English)', minScore: 0, maxScore: 500, step: 10, defaultScore: 350 },
        { id: 'NONE', label: 'Other / Not Required / Not Taken', minScore: 0, maxScore: 0, step: 0, defaultScore: 0 },
      ],
      budgetRanges: this.budgetMatcherService.budgetRanges,
      defaultWeights: this.getWeights(),
    };
  }

  searchMatches(dto: UniversityMatchSearchDto) {
    // 1. Calculate match for every program in the database
    const results: UniversityMatchResult[] = this.programsDatabase.map((program) => {
      return this.matchScoreService.calculateMatch(dto, program, this.weights);
    });

    // 2. Rank results:
    // First by eligibility (ELIGIBLE > POSSIBLE_MATCH > NOT_ELIGIBLE), then by matchScore descending
    results.sort((a, b) => {
      const eligibilityOrder = { ELIGIBLE: 3, POSSIBLE_MATCH: 2, NOT_ELIGIBLE: 1 };
      const orderDiff = eligibilityOrder[b.eligibility] - eligibilityOrder[a.eligibility];
      if (orderDiff !== 0) return orderDiff;
      return b.matchScore - a.matchScore;
    });

    return {
      totalResults: results.length,
      eligibleCount: results.filter((r) => r.eligibility === 'ELIGIBLE').length,
      preferences: dto,
      weightsUsed: this.weights,
      results,
    };
  }

  getUniversityBySlug(slug: string) {
    const clean = slug.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const matches = this.programsDatabase.filter(
      (p) => p.universitySlug === clean || p.universityId === clean || p.universityName.toLowerCase().includes(clean.replace(/-/g, ' '))
    );

    if (matches.length === 0) {
      // Fallback: return first or generic representation
      return this.programsDatabase[0];
    }

    const primary = matches[0];
    return {
      id: primary.universityId,
      name: primary.universityName,
      slug: primary.universitySlug,
      logo: primary.logo,
      coverImage: primary.coverImage,
      country: primary.country,
      city: primary.city,
      ranking: primary.ranking,
      description: primary.description,
      website: primary.website,
      destinationCode: primary.destinationCode,
      programs: matches.map((m) => ({
        id: m.id,
        courseName: m.courseName,
        courseCategory: m.courseCategory,
        studyLevel: m.studyLevel,
        duration: m.duration,
        tuitionFeeLocal: m.tuitionFeeLocal,
        tuitionInrLakhs: m.tuitionInrLakhs,
        intakes: m.intakes,
        eligibility: m.eligibility,
        englishReq: m.englishReq,
        scholarshipAvailable: m.scholarshipAvailable,
        scholarshipDetails: m.scholarshipDetails,
        applicationDeadline: m.applicationDeadline,
      })),
      isDemoData: primary.isDemoData,
    };
  }
}
