import os
import shutil

BASE_DIR = r"c:\Users\PUJI KRISHNA\OneDrive\Desktop\Aegies\aegis-overseas"

directories = [
    r"storage\images",
    r"storage\documents",
    r"storage\videos",
    r"docs",
    r"scripts",
    r"database\seed",
    r"database\backups",
    
    # backend
    r"backend\src\config",
    r"backend\src\auth\guards",
    r"backend\src\auth\strategies",
    r"backend\src\auth\dto",
    r"backend\src\users\entities",
    r"backend\src\users\dto",
    r"backend\src\leads\entities",
    r"backend\src\leads\dto",
    r"backend\src\students\entities",
    r"backend\src\students\dto",
    r"backend\src\universities\entities",
    r"backend\src\universities\dto",
    r"backend\src\courses",
    r"backend\src\destinations",
    r"backend\src\scholarships",
    r"backend\src\services",
    r"backend\src\test-preparation",
    r"backend\src\testimonials",
    r"backend\src\student-stories",
    r"backend\src\blog",
    r"backend\src\enquiries",
    r"backend\src\consultations",
    r"backend\src\applications",
    r"backend\src\documents",
    r"backend\src\media",
    r"backend\src\notifications",
    r"backend\src\analytics",
    r"backend\src\seo",
    r"backend\src\settings",
    r"backend\src\audit-logs",
    r"backend\prisma\migrations",
    r"backend\uploads\images",
    r"backend\uploads\documents",
    r"backend\uploads\videos",
    r"backend\test\unit",
    r"backend\test\e2e",
    
    # admin
    r"admin\src\pages\Login",
    r"admin\src\pages\Dashboard",
    r"admin\src\pages\Leads",
    r"admin\src\pages\Students",
    r"admin\src\pages\Applications",
    r"admin\src\pages\Universities",
    r"admin\src\pages\Courses",
    r"admin\src\pages\Destinations",
    r"admin\src\pages\Scholarships",
    r"admin\src\pages\Services",
    r"admin\src\pages\Testimonials",
    r"admin\src\pages\StudentStories",
    r"admin\src\pages\Blog",
    r"admin\src\pages\FAQs",
    r"admin\src\pages\Media",
    r"admin\src\pages\Consultations",
    r"admin\src\pages\Reports",
    r"admin\src\pages\Notifications",
    r"admin\src\pages\Settings",
    r"admin\src\components",
    r"admin\src\services",
    r"admin\src\hooks",
    r"admin\src\types",
    r"admin\src\utils",
    
    # frontend public
    r"frontend\public\favicon",
    r"frontend\public\logos",
    r"frontend\public\images\hero",
    r"frontend\public\images\destinations",
    r"frontend\public\images\universities",
    r"frontend\public\images\courses",
    r"frontend\public\images\services",
    r"frontend\public\images\scholarships",
    r"frontend\public\images\students",
    r"frontend\public\images\testimonials",
    r"frontend\public\images\blog",
    r"frontend\public\icons\countries",
    r"frontend\public\icons\services",
    r"frontend\public\icons\courses",
    r"frontend\public\icons\social",
    r"frontend\public\icons\ui",
    r"frontend\public\flags",
    r"frontend\public\videos",
    
    # frontend src
    r"frontend\src\pages\Home",
    r"frontend\src\pages\About",
    r"frontend\src\pages\Destinations",
    r"frontend\src\pages\Universities",
    r"frontend\src\pages\Courses",
    r"frontend\src\pages\Services",
    r"frontend\src\pages\Scholarships",
    r"frontend\src\pages\TestPreparation",
    r"frontend\src\pages\StudentStories",
    r"frontend\src\pages\Blog",
    r"frontend\src\pages\UniversityFinder",
    r"frontend\src\pages\Consultation",
    r"frontend\src\pages\Contact",
    r"frontend\src\pages\Privacy",
    r"frontend\src\pages\Terms",
    r"frontend\src\components\layout",
    r"frontend\src\components\home",
    r"frontend\src\components\destinations",
    r"frontend\src\components\universities",
    r"frontend\src\components\courses",
    r"frontend\src\components\services",
    r"frontend\src\components\scholarships",
    r"frontend\src\components\test-preparation",
    r"frontend\src\components\student-stories",
    r"frontend\src\components\testimonials",
    r"frontend\src\components\blog",
    r"frontend\src\components\forms",
    r"frontend\src\components\common",
    r"frontend\src\components\ui",
    r"frontend\src\hooks",
    r"frontend\src\services",
    r"frontend\src\types",
    r"frontend\src\config",
    r"frontend\src\utils"
]

for d in directories:
    target = os.path.join(BASE_DIR, d)
    os.makedirs(target, exist_ok=True)

print(f"Created {len(directories)} directories successfully.")
